services:
  agent:
    container_name: portainer-agent
    image: portainer/agent:2.26.0
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - "9001:9001"
