services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.9.6
    container_name: homepage
    ports:
      - 3044:3000
    env_file: .env
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`homepage.tromso.snerre`)"
      - "traefik.http.routers.homepage.entrypoints=web"
    environment:
      PUID: $PUID
      PGID: $PGID
    restart: unless-stopped
