services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.5.0
    container_name: homepage
    ports:
      - 3044:3000
    env_file: .env
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`$HOMEPAGE_VAR_URL`)"
      - "traefik.http.routers.homepage.entrypoints=web"
    environment:
      PUID: $HOMEPAGE_VAR_PUID
      PGID: $HOMEPAGE_VAR_PGID
      HOMEPAGE_ALLOWED_HOSTS: $HOMEPAGE_VAR_HOMEPAGE_ALLOWED_HOSTS
    restart: unless-stopped
