services:
  zabbix-proxy:
    image: zabbix/zabbix-proxy-sqlite3:alpine-7.0.3
    container_name: zabbix-proxy
    restart: unless-stopped
    network_mode: host
    env_file: .env
    environment:
      - DB_SERVER_HOST=localhost
      - ZBX_SERVER_HOST=$ZABBIX_PROXY_VAR_SERVER_HOST
      - ZBX_SERVER_PORT=10051
      - ZBX_HOSTNAME=$ZABBIX_PROXY_VAR_HOSTNAME
      - ZBX_PROXYMODE=0  # 0 - active, 1 - passive
      - ZBX_PROXYCONFIGFREQUENCY=3600
      - ZBX_PROXYDATACOLLECTFREQUENCY=1
      - ZBX_STARTPOLLERS=5
      - ZBX_STARTPINGERS=1
      - ZBX_STARTDISCOVERERS=1
      - ZBX_STARTHTTPPOLLERS=1
      - ZBX_CACHESIZE=8M
      - ZBX_STARTDBSYNCERS=4
      - ZBX_HISTORYCACHESIZE=16M
      - ZBX_HISTORYINDEXCACHESIZE=4M
      - ZBX_LOGSLOWQUERIES=3000
      - ZBX_TLSPSKIDENTITY=$ZABBIX_PROXY_VAR_TLSPSKIDENTITY
      - ZBX_TLSPSKFILE=/var/lib/zabbix/enc/psk
      - ZBX_TLSCONNECT=psk
      - ZBX_TIMEOUT=10
    volumes:
      - ./db_data:/var/lib/zabbix/db_data
      - ./enc:/var/lib/zabbix/enc

