services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:2.1.0
    restart: unless-stopped
    privileged: true
    volumes:
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8280:8080
    environment:
      - TZ=$ZIGBEE2MQTT_VAR_TZ
      - PUID=$ZIGBEE2MQTT_VAR_PUID
      - PGID=$ZIGBEE2MQTT_VAR_PGID
    devices:
      # Make sure this matched your adapter location
      - $ZIGBEE2MQTT_VAR_DONGLE:/dev/ttyACM0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zigbee2mqtt.rule=Host(`$ZIGBEE2MQTT_VAR_HOSTNAME`)"
      - "traefik.http.routers.zigbee2mqtt.entrypoints=web"
