services:
  mosquitto:
    image: eclipse-mosquitto:2.0.17
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    env_file: .env
    user: "$MOSQUITTO_VAR_PUID:$MOSQUITTO_VAR_PGID"
    ports:
      - "1883:1883"
      - "9901:9001"
    volumes:
      - ./mosquitto:/etc/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

