services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz
    container_name: netbootxyz
    environment:
      - MENU_VERSION=2.0.47 # optional
    volumes:
      - ./config:/config # optional
      - ./assets:/assets # optional
    ports:
      - 3150:3000 # Webapp
      - 69:69/udp
#      - 8080:80 #optional nginx port.
    restart: unless-stopped

