services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz:0.7.6-nbxyz1
    container_name: netboot
    env_file: .env
    #environment:
    #  - MENU_VERSION=2.0.47 # optional
    volumes:
      - ./config:/config # optional
      - ./assets:/assets # optional
    ports:
      - 3150:3000 # Webapp
      - 69:69/udp
#      - 8080:80 #optional nginx port.
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.netboot.rule=Host(`$NETBOOT_VAR_URL`)"
      - "traefik.http.routers.netboot.entrypoints=web"

