services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2025.10.2
    env_file: .env
    #network_mode: host

    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "3380:80/tcp"
    environment:
      TZ: '$PIHOLE_VAR_TZ'
      WEBPASSWORD: $PIHOLE_VAR_WEBPASS
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`$PIHOLE_VAR_HOSTNAME`)"
      - "traefik.http.routers.pihole.entrypoints=web"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"

  piexporter:
    container_name: piexporter
    image: ekofr/pihole-exporter:v1.2.0
    env_file: .env
    restart: unless-stopped
    ports:
      - 9617:9617
    environment:
      PIHOLE_PASSWORD: $PIHOLE_VAR_WEBPASS
      PIHOLE_HOSTNAME: $PIHOLE_VAR_HOSTNAME
