#!/bin/bash

#
## Script for å sende ku til cecilie
#

if [ "$#" -eq 0 ]; then
    echo "Usage: $0 text"
fi


clear
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo


/usr/games/cowsay $1


echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
